description: A Helm chart for Mastodon
name: mastodon
sources:
- https://github.com/timwalls/mastodon-chart
- https://github.com/tootsuite/mastodon
maintainers:
- email: tim.walls@snowgoons.com
  name: timwalls
version: 1.0.0
engine: gotpl
