web:
  name: web

streaming:
  name: streaming

sidekiq:
  name: sidekiq

redis:
  name: redis
  image: bitnami/redis
  imageTag: 3.2.8-r2
  imagePullPolicy: IfNotPresent
  # You need to create PV beforehead.
  persistentVolume:
    accessMode: ReadWriteMany
    size: 8Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m

postgres:
  name: postgres
  image: postgres
  imageTag: 9.6.2
  imagePullPolicy: IfNotPresent
  env:
    postgres_user: "postgres"
    pguser: "postgres"
    postgres_db: ""
    pgdata: /var/lib/postgresql/data/pgdata
  # You need to create PV beforehead.
  persistentVolume:
    accessMode: ReadWriteMany
    size: 8Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
  metrics:
    enabled: true
    image: wrouesnel/postgres_exporter
    imageTag: v0.1.1
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
