apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: {{ template "name" . }}-daily-cron
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ template "name" . }}-daily-cron
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    metadata:
      labels:
        app: {{ template "name" . }}
        component: {{ template "name" . }}-daily-cron
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ template "name" . }}-daily-cron
        image: "{{ .Values.web.image }}:{{ .Values.web.imageTag }}"
        imagePullPolicy: {{ .Values.web.imagePullPolicy | quote }}
        command:
          - bundle
          - exec
          - rake
          - mastodon:daily
        env:
{{ include "productonEnvironment" . | indent 8 }}
        volumeMounts:
        - name: assets
          mountPath: /mastodon/public/assets
        - name: system
          mountPath: /mastodon/public/system
      volumes:
      - name: system
        persistentVolumeClaim:
          claimName: {{ template "web.fullname" . }}-system
      - name: assets
        persistentVolumeClaim:
          claimName: {{ template "web.fullname" . }}-assets
