apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgres.fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.postgres.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresPassword | b64enc | quote }}
