apiVersion: v1
kind: Service
metadata:
  name: {{ template "postgres.fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.postgres.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
  - name: postgresql
    port: {{ .Values.postgres.servicePort }}
    targetPort: postgresql
  selector:
    app: {{ template "name" . }}
    component: "{{ .Values.postgres.name }}"
    release: {{ .Release.Name }}
