apiVersion: v1
kind: Secret
metadata:
  name: {{ template "redis.fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.redis.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  redis-password: {{ .Values.redisPassword | b64enc | quote }}
