apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.streaming.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "streaming.fullname" . }}
spec:
  ports:
    - name: http
      port: {{ .Values.streaming.servicePort }}
      targetPort: streaming
  selector:
    app: {{ template "name" . }}
    component: "{{ .Values.streaming.name }}"
    release: {{ .Release.Name }}
  type: "ClusterIP"
