apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.web.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "web.fullname" . }}
spec:
  rules:
  - host: mastodon.ladicle.com
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-{{ template "web.fullname" }}
          servicePort: 80
  tls:
  - secretName: test-lego-secret
    hosts:
    - mastodon.ladicle.com
