apiVersion: v1
kind: Secret
metadata:
  name: {{ template "web.fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.web.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  paperclipSecret: {{ .Values.secrets.paperclipSecret | b64enc | quote }}
  secretKeyBase: {{ .Values.secrets.secretKeyBase | b64enc | quote }}
  otpSecret: {{ .Values.secrets.otpSecret | b64enc | quote }}
  smtpPassword: {{ .Values.secrets.smtpPassword | b64enc | quote }}
